$(document).ready(function(){
	$('#okforgot').click(function(){
    	$('#login').addClass("reg");
    	$('#forgot').removeClass("reg");
  	});
	$('#oklogin2').on("click",function(){
    	$('#forgot').addClass("reg");
    	$('#login').removeClass("reg");
  	});
});